version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: subscriptions
      POSTGRES_USER: subscriptions
      POSTGRES_PASSWORD: subscriptions
    ports:
      - "5432:5432"
    container_name: subscriptions-postgres-dev