spring:
  datasource:
    hikari:
      maximum-pool-size: 3
      connection-timeout: 2000
    url: jdbc:postgresql://localhost:5432/subscriptions
    username: subscriptions
    password: subscriptions
  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml
    enabled: true
springdoc:
  packages-to-scan: org.example.subscriptions.service.controller
  paths-to-match: /**
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

most-popular-subscriptions-request-limit: 3